# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-06-07 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.validate


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=150, validators=[tweets.validate.validate_content]),
        ),
    ]
